name: Applied AR
favicon: null
layout_spectrum: 0.8890152538660914
typography_spectrum: 0.8123904941603541
title: Applied Augmented Reality
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41864767111837864
  lightness: 0.30517289438284934
  saturation: 0.15940819843672216
  rhythmicContrast: 0.9453558747190982
purpose: []
